// OpenGL 3.3 core function loader (via SDL_GL_GetProcAddress, prototypes from GL/glcorearb.h — no GLEW / glad).
#pragma once
#undef GL_GLEXT_PROTOTYPES
#include <GL/glcorearb.h>

#define SB_GL_FUNCS(X) \
  X(PFNGLCLEARPROC, glClear) X(PFNGLCLEARCOLORPROC, glClearColor) X(PFNGLCLEARDEPTHPROC, glClearDepth) \
  X(PFNGLVIEWPORTPROC, glViewport) X(PFNGLENABLEPROC, glEnable) X(PFNGLDISABLEPROC, glDisable) \
  X(PFNGLSCISSORPROC, glScissor) \
  X(PFNGLBLENDFUNCPROC, glBlendFunc) X(PFNGLBLENDFUNCSEPARATEPROC, glBlendFuncSeparate) X(PFNGLDEPTHFUNCPROC, glDepthFunc) \
  X(PFNGLBLENDEQUATIONSEPARATEPROC, glBlendEquationSeparate) X(PFNGLBLENDCOLORPROC, glBlendColor) \
  X(PFNGLDEPTHMASKPROC, glDepthMask) X(PFNGLCULLFACEPROC, glCullFace) X(PFNGLPOLYGONOFFSETPROC, glPolygonOffset) \
  X(PFNGLGETINTEGERVPROC, glGetIntegerv) X(PFNGLGETSTRINGPROC, glGetString) X(PFNGLGETSTRINGIPROC, glGetStringi) X(PFNGLGETERRORPROC, glGetError) \
  X(PFNGLCOLORMASKPROC, glColorMask) X(PFNGLDRAWBUFFERSPROC, glDrawBuffers) X(PFNGLREADBUFFERPROC, glReadBuffer) \
  X(PFNGLREADPIXELSPROC, glReadPixels) X(PFNGLPIXELSTOREIPROC, glPixelStorei) \
  X(PFNGLGENBUFFERSPROC, glGenBuffers) X(PFNGLDELETEBUFFERSPROC, glDeleteBuffers) X(PFNGLBINDBUFFERPROC, glBindBuffer) \
  X(PFNGLBUFFERDATAPROC, glBufferData) X(PFNGLBUFFERSUBDATAPROC, glBufferSubData) \
  X(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays) X(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays) X(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray) \
  X(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray) X(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer) \
  X(PFNGLVERTEXATTRIBIPOINTERPROC, glVertexAttribIPointer) X(PFNGLVERTEXATTRIBDIVISORPROC, glVertexAttribDivisor) \
  X(PFNGLVERTEXATTRIB4FPROC, glVertexAttrib4f) \
  X(PFNGLDRAWARRAYSPROC, glDrawArrays) X(PFNGLDRAWELEMENTSPROC, glDrawElements) \
  X(PFNGLDRAWELEMENTSINSTANCEDPROC, glDrawElementsInstanced) X(PFNGLDRAWARRAYSINSTANCEDPROC, glDrawArraysInstanced) \
  X(PFNGLCREATESHADERPROC, glCreateShader) X(PFNGLSHADERSOURCEPROC, glShaderSource) X(PFNGLCOMPILESHADERPROC, glCompileShader) \
  X(PFNGLGETSHADERIVPROC, glGetShaderiv) X(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog) X(PFNGLDELETESHADERPROC, glDeleteShader) \
  X(PFNGLCREATEPROGRAMPROC, glCreateProgram) X(PFNGLATTACHSHADERPROC, glAttachShader) X(PFNGLLINKPROGRAMPROC, glLinkProgram) \
  X(PFNGLGETPROGRAMIVPROC, glGetProgramiv) X(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog) X(PFNGLUSEPROGRAMPROC, glUseProgram) \
  X(PFNGLDELETEPROGRAMPROC, glDeleteProgram) X(PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation) \
  X(PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation) X(PFNGLGETACTIVEUNIFORMPROC, glGetActiveUniform) \
  X(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation) X(PFNGLUNIFORM1IPROC, glUniform1i) X(PFNGLUNIFORM1FPROC, glUniform1f) \
  X(PFNGLUNIFORM2FPROC, glUniform2f) X(PFNGLUNIFORM3FPROC, glUniform3f) X(PFNGLUNIFORM4FPROC, glUniform4f) \
  X(PFNGLUNIFORM1FVPROC, glUniform1fv) X(PFNGLUNIFORM2FVPROC, glUniform2fv) X(PFNGLUNIFORM3FVPROC, glUniform3fv) X(PFNGLUNIFORM4FVPROC, glUniform4fv) \
  X(PFNGLUNIFORM1IVPROC, glUniform1iv) X(PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv) X(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv) \
  X(PFNGLGENTEXTURESPROC, glGenTextures) X(PFNGLDELETETEXTURESPROC, glDeleteTextures) X(PFNGLBINDTEXTUREPROC, glBindTexture) \
  X(PFNGLACTIVETEXTUREPROC, glActiveTexture) X(PFNGLTEXIMAGE2DPROC, glTexImage2D) X(PFNGLTEXIMAGE3DPROC, glTexImage3D) \
  X(PFNGLTEXPARAMETERIPROC, glTexParameteri) X(PFNGLTEXPARAMETERFPROC, glTexParameterf) X(PFNGLTEXPARAMETERFVPROC, glTexParameterfv) \
  X(PFNGLGENERATEMIPMAPPROC, glGenerateMipmap) \
  X(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers) X(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers) X(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer) \
  X(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D) X(PFNGLFRAMEBUFFERTEXTURELAYERPROC, glFramebufferTextureLayer) \
  X(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus) \
  X(PFNGLGENRENDERBUFFERSPROC, glGenRenderbuffers) X(PFNGLBINDRENDERBUFFERPROC, glBindRenderbuffer) X(PFNGLDELETERENDERBUFFERSPROC, glDeleteRenderbuffers) \
  X(PFNGLRENDERBUFFERSTORAGEPROC, glRenderbufferStorage) X(PFNGLFRAMEBUFFERRENDERBUFFERPROC, glFramebufferRenderbuffer) \
  X(PFNGLBLITFRAMEBUFFERPROC, glBlitFramebuffer)

#define SB_GL_DECL(T, N) extern T N;
SB_GL_FUNCS(SB_GL_DECL)
#undef SB_GL_DECL
// optional (GL 4.5 / ARB_clip_control): reversed-Z depth
typedef void (APIENTRYP PFNGLCLIPCONTROLPROC_)(GLenum origin, GLenum depth);
extern PFNGLCLIPCONTROLPROC_ glClipControl_;

bool glLoad(); // after context creation
bool glHasClipControl(); // GL >= 4.5 or ARB_clip_control
